// /// **Get category name based on color**
// String getCategory(Color color) {
//   if (color == Colors.red) return "Alkali Metals";
//   if (color == Colors.orange) return "Alkaline Earth Metals";
//   if (color == Colors.amber) return "Transition Metals";
//   if (color == Colors.purple) return "Metalloids";
//   if (color == Colors.green) return "Nonmetals";
//   if (color == Colors.blue) return "Halogens";
//   if (color == Colors.cyan) return "Noble Gases";
//   return "Unknown";
// }

import 'package:flutter/material.dart';

class PeriodicElement {
  final String symbol;
  final String name;
  final int atomicNumber;
  final Color color;
  final double atomicMass;
  final double? meltingPoint; // in Kelvin
  final double? boilingPoint; // in Kelvin
  final double? electronegativity;

  const PeriodicElement({
    required this.symbol,
    required this.name,
    required this.atomicNumber,
    required this.color,
    required this.atomicMass,
    this.meltingPoint,
    this.boilingPoint,
    this.electronegativity,
  });
}

List<List<PeriodicElement?>> periodicTable = [
  [
    PeriodicElement(
      symbol: 'H',
      name: 'Hydrogen',
      atomicNumber: 1,
      color: Colors.blue,
      atomicMass: 1.008,
      meltingPoint: 14.01,
      boilingPoint: 20.28,
      electronegativity: 2.20,
    ),
    PeriodicElement(
      symbol: 'He',
      name: 'Helium',
      atomicNumber: 2,
      color: Colors.cyan,
      atomicMass: 4.0026,
      meltingPoint: 0.95,
      boilingPoint: 4.22,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Li',
      name: 'Lithium',
      atomicNumber: 3,
      color: Colors.lime,
      atomicMass: 6.94,
      meltingPoint: 453.69,
      boilingPoint: 1615,
      electronegativity: 0.98,
    ),
    PeriodicElement(
      symbol: 'Be',
      name: 'Beryllium',
      atomicNumber: 4,
      color: Colors.orange,
      atomicMass: 9.0122,
      meltingPoint: 1560,
      boilingPoint: 2742,
      electronegativity: 1.57,
    ),
    PeriodicElement(
      symbol: 'B',
      name: 'Boron',
      atomicNumber: 5,
      color: Colors.purple,
      atomicMass: 10.81,
      meltingPoint: 2349,
      boilingPoint: 4200,
      electronegativity: 2.04,
    ),
    PeriodicElement(
      symbol: 'C',
      name: 'Carbon',
      atomicNumber: 6,
      color: Colors.green,
      atomicMass: 12.011,
      meltingPoint: 3915,
      boilingPoint: 3915,
      electronegativity: 2.55,
    ),
    PeriodicElement(
      symbol: 'N',
      name: 'Nitrogen',
      atomicNumber: 7,
      color: Colors.green,
      atomicMass: 14.007,
      meltingPoint: 63.15,
      boilingPoint: 77.36,
      electronegativity: 3.04,
    ),
    PeriodicElement(
      symbol: 'O',
      name: 'Oxygen',
      atomicNumber: 8,
      color: Colors.green,
      atomicMass: 15.999,
      meltingPoint: 54.36,
      boilingPoint: 90.20,
      electronegativity: 3.44,
    ),
    PeriodicElement(
      symbol: 'F',
      name: 'Fluorine',
      atomicNumber: 9,
      color: Colors.blue,
      atomicMass: 18.998,
      meltingPoint: 53.48,
      boilingPoint: 85.03,
      electronegativity: 3.98,
    ),
    PeriodicElement(
      symbol: 'Ne',
      name: 'Neon',
      atomicNumber: 10,
      color: Colors.cyan,
      atomicMass: 20.180,
      meltingPoint: 24.56,
      boilingPoint: 27.07,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Na',
      name: 'Sodium',
      atomicNumber: 11,
      color: Colors.lime,
      atomicMass: 22.990,
      meltingPoint: 370.87,
      boilingPoint: 1156,
      electronegativity: 0.93,
    ),
    PeriodicElement(
      symbol: 'Mg',
      name: 'Magnesium',
      atomicNumber: 12,
      color: Colors.orange,
      atomicMass: 24.305,
      meltingPoint: 923,
      boilingPoint: 1380,
      electronegativity: 1.31,
    ),
    PeriodicElement(
      symbol: 'Al',
      name: 'Aluminium',
      atomicNumber: 13,
      color: Colors.purple,
      atomicMass: 26.982,
      meltingPoint: 933.47,
      boilingPoint: 2792,
      electronegativity: 1.61,
    ),
    PeriodicElement(
      symbol: 'Si',
      name: 'Silicon',
      atomicNumber: 14,
      color: Colors.green,
      atomicMass: 28.085,
      meltingPoint: 1687,
      boilingPoint: 3538,
      electronegativity: 1.90,
    ),
    PeriodicElement(
      symbol: 'P',
      name: 'Phosphorus',
      atomicNumber: 15,
      color: Colors.green,
      atomicMass: 30.974,
      meltingPoint: 317.3,
      boilingPoint: 550,
      electronegativity: 2.19,
    ),
    PeriodicElement(
      symbol: 'S',
      name: 'Sulfur',
      atomicNumber: 16,
      color: Colors.green,
      atomicMass: 32.06,
      meltingPoint: 388.36,
      boilingPoint: 717.87,
      electronegativity: 2.58,
    ),
    PeriodicElement(
      symbol: 'Cl',
      name: 'Chlorine',
      atomicNumber: 17,
      color: Colors.blue,
      atomicMass: 35.45,
      meltingPoint: 171.6,
      boilingPoint: 239.11,
      electronegativity: 3.16,
    ),
    PeriodicElement(
      symbol: 'Ar',
      name: 'Argon',
      atomicNumber: 18,
      color: Colors.cyan,
      atomicMass: 39.948,
      meltingPoint: 83.81,
      boilingPoint: 87.30,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'K',
      name: 'Potassium',
      atomicNumber: 19,
      color: Colors.lime,
      atomicMass: 39.098,
      meltingPoint: 336.53,
      boilingPoint: 1032,
      electronegativity: 0.82,
    ),
    PeriodicElement(
      symbol: 'Ca',
      name: 'Calcium',
      atomicNumber: 20,
      color: Colors.orange,
      atomicMass: 40.078,
      meltingPoint: 1115,
      boilingPoint: 1757,
      electronegativity: 1.00,
    ),
    PeriodicElement(
      symbol: 'Sc',
      name: 'Scandium',
      atomicNumber: 21,
      color: Colors.amber,
      atomicMass: 44.956,
      meltingPoint: 1814,
      boilingPoint: 3109,
      electronegativity: 1.36,
    ),
    PeriodicElement(
      symbol: 'Ti',
      name: 'Titanium',
      atomicNumber: 22,
      color: Colors.amber,
      atomicMass: 47.867,
      meltingPoint: 1941,
      boilingPoint: 3560,
      electronegativity: 1.54,
    ),
    PeriodicElement(
      symbol: 'V',
      name: 'Vanadium',
      atomicNumber: 23,
      color: Colors.amber,
      atomicMass: 50.942,
      meltingPoint: 2183,
      boilingPoint: 3680,
      electronegativity: 1.63,
    ),
    PeriodicElement(
      symbol: 'Cr',
      name: 'Chromium',
      atomicNumber: 24,
      color: Colors.amber,
      atomicMass: 51.996,
      meltingPoint: 2180,
      boilingPoint: 2944,
      electronegativity: 1.66,
    ),
    PeriodicElement(
      symbol: 'Mn',
      name: 'Manganese',
      atomicNumber: 25,
      color: Colors.amber,
      atomicMass: 54.938,
      meltingPoint: 1519,
      boilingPoint: 2334,
      electronegativity: 1.55,
    ),
    PeriodicElement(
      symbol: 'Fe',
      name: 'Iron',
      atomicNumber: 26,
      color: Colors.amber,
      atomicMass: 55.845,
      meltingPoint: 1811,
      boilingPoint: 3134,
      electronegativity: 1.83,
    ),
    PeriodicElement(
      symbol: 'Co',
      name: 'Cobalt',
      atomicNumber: 27,
      color: Colors.amber,
      atomicMass: 58.933,
      meltingPoint: 1768,
      boilingPoint: 3200,
      electronegativity: 1.88,
    ),
    PeriodicElement(
      symbol: 'Ni',
      name: 'Nickel',
      atomicNumber: 28,
      color: Colors.amber,
      atomicMass: 58.693,
      meltingPoint: 1728,
      boilingPoint: 3186,
      electronegativity: 1.91,
    ),
    PeriodicElement(
      symbol: 'Cu',
      name: 'Copper',
      atomicNumber: 29,
      color: Colors.amber,
      atomicMass: 63.546,
      meltingPoint: 1357.77,
      boilingPoint: 2835,
      electronegativity: 1.90,
    ),
    PeriodicElement(
      symbol: 'Zn',
      name: 'Zinc',
      atomicNumber: 30,
      color: Colors.amber,
      atomicMass: 65.38,
      meltingPoint: 692.68,
      boilingPoint: 1180,
      electronegativity: 1.65,
    ),
    PeriodicElement(
      symbol: 'Ga',
      name: 'Gallium',
      atomicNumber: 31,
      color: Colors.purple,
      atomicMass: 69.723,
      meltingPoint: 302.91,
      boilingPoint: 2477,
      electronegativity: 1.81,
    ),
    PeriodicElement(
      symbol: 'Ge',
      name: 'Germanium',
      atomicNumber: 32,
      color: Colors.green,
      atomicMass: 72.630,
      meltingPoint: 1211.40,
      boilingPoint: 3106,
      electronegativity: 2.01,
    ),
    PeriodicElement(
      symbol: 'As',
      name: 'Arsenic',
      atomicNumber: 33,
      color: Colors.green,
      atomicMass: 74.922,
      meltingPoint: 1090,
      boilingPoint: 887,
      electronegativity: 2.18,
    ),
    PeriodicElement(
      symbol: 'Se',
      name: 'Selenium',
      atomicNumber: 34,
      color: Colors.green,
      atomicMass: 78.971,
      meltingPoint: 494,
      boilingPoint: 958,
      electronegativity: 2.55,
    ),
    PeriodicElement(
      symbol: 'Br',
      name: 'Bromine',
      atomicNumber: 35,
      color: Colors.blue,
      atomicMass: 79.904,
      meltingPoint: 265.8,
      boilingPoint: 332,
      electronegativity: 2.96,
    ),
    PeriodicElement(
      symbol: 'Kr',
      name: 'Krypton',
      atomicNumber: 36,
      color: Colors.cyan,
      atomicMass: 83.798,
      meltingPoint: 115.79,
      boilingPoint: 119.93,
      electronegativity: 3.00,
    ),
    PeriodicElement(
      symbol: 'Rb',
      name: 'Rubidium',
      atomicNumber: 37,
      color: Colors.lime,
      atomicMass: 85.468,
      meltingPoint: 312.46,
      boilingPoint: 961,
      electronegativity: 0.82,
    ),
    PeriodicElement(
      symbol: 'Sr',
      name: 'Strontium',
      atomicNumber: 38,
      color: Colors.orange,
      atomicMass: 87.62,
      meltingPoint: 1050,
      boilingPoint: 1655,
      electronegativity: 0.95,
    ),
    PeriodicElement(
      symbol: 'Y',
      name: 'Yttrium',
      atomicNumber: 39,
      color: Colors.amber,
      atomicMass: 88.906,
      meltingPoint: 1799,
      boilingPoint: 3609,
      electronegativity: 1.22,
    ),
    PeriodicElement(
      symbol: 'Zr',
      name: 'Zirconium',
      atomicNumber: 40,
      color: Colors.amber,
      atomicMass: 91.224,
      meltingPoint: 2128,
      boilingPoint: 4682,
      electronegativity: 1.33,
    ),
    PeriodicElement(
      symbol: 'Nb',
      name: 'Niobium',
      atomicNumber: 41,
      color: Colors.amber,
      atomicMass: 92.906,
      meltingPoint: 2750,
      boilingPoint: 5017,
      electronegativity: 1.6,
    ),
    PeriodicElement(
      symbol: 'Mo',
      name: 'Molybdenum',
      atomicNumber: 42,
      color: Colors.amber,
      atomicMass: 95.95,
      meltingPoint: 2896,
      boilingPoint: 4912,
      electronegativity: 2.16,
    ),
    PeriodicElement(
      symbol: 'Tc',
      name: 'Technetium',
      atomicNumber: 43,
      color: Colors.amber,
      atomicMass: 98,
      meltingPoint: 2430,
      boilingPoint: 4538,
      electronegativity: 1.9,
    ),
    PeriodicElement(
      symbol: 'Ru',
      name: 'Ruthenium',
      atomicNumber: 44,
      color: Colors.amber,
      atomicMass: 101.07,
      meltingPoint: 2607,
      boilingPoint: 4423,
      electronegativity: 2.2,
    ),
    PeriodicElement(
      symbol: 'Rh',
      name: 'Rhodium',
      atomicNumber: 45,
      color: Colors.amber,
      atomicMass: 102.91,
      meltingPoint: 2237,
      boilingPoint: 3968,
      electronegativity: 2.28,
    ),
    PeriodicElement(
      symbol: 'Pd',
      name: 'Palladium',
      atomicNumber: 46,
      color: Colors.amber,
      atomicMass: 106.42,
      meltingPoint: 1828,
      boilingPoint: 3236,
      electronegativity: 2.20,
    ),
    PeriodicElement(
      symbol: 'Ag',
      name: 'Silver',
      atomicNumber: 47,
      color: Colors.amber,
      atomicMass: 107.87,
      meltingPoint: 1234.93,
      boilingPoint: 2435,
      electronegativity: 1.93,
    ),
    PeriodicElement(
      symbol: 'Sn',
      name: 'Tin',
      atomicNumber: 50,
      color: Colors.green,
      atomicMass: 118.71,
      meltingPoint: 505.08,
      boilingPoint: 2875,
      electronegativity: 1.96,
    ),
    PeriodicElement(
      symbol: 'Sb',
      name: 'Antimony',
      atomicNumber: 51,
      color: Colors.green,
      atomicMass: 121.76,
      meltingPoint: 903.78,
      boilingPoint: 1860,
      electronegativity: 2.05,
    ),
    PeriodicElement(
      symbol: 'Te',
      name: 'Tellurium',
      atomicNumber: 52,
      color: Colors.green,
      atomicMass: 127.60,
      meltingPoint: 722.66,
      boilingPoint: 1261,
      electronegativity: 2.1,
    ),
    PeriodicElement(
      symbol: 'I',
      name: 'Iodine',
      atomicNumber: 53,
      color: Colors.blue,
      atomicMass: 126.90,
      meltingPoint: 386.85,
      boilingPoint: 457.4,
      electronegativity: 2.66,
    ),
    PeriodicElement(
      symbol: 'Xe',
      name: 'Xenon',
      atomicNumber: 54,
      color: Colors.cyan,
      atomicMass: 131.29,
      meltingPoint: 161.4,
      boilingPoint: 165.03,
      electronegativity: 2.6,
    ),
    PeriodicElement(
      symbol: 'Cs',
      name: 'Caesium',
      atomicNumber: 55,
      color: Colors.lime,
      atomicMass: 132.91,
      meltingPoint: 301.7,
      boilingPoint: 944,
      electronegativity: 0.79,
    ),
    PeriodicElement(
      symbol: 'Ba',
      name: 'Barium',
      atomicNumber: 56,
      color: Colors.orange,
      atomicMass: 137.33,
      meltingPoint: 1000,
      boilingPoint: 2170,
      electronegativity: 0.89,
    ),
    PeriodicElement(
      symbol: 'La',
      name: 'Lanthanum',
      atomicNumber: 57,
      color: Colors.purple,
      atomicMass: 138.91,
      meltingPoint: 1193,
      boilingPoint: 3737,
      electronegativity: 1.10,
    ),
    PeriodicElement(
      symbol: 'Ce',
      name: 'Cerium',
      atomicNumber: 58,
      color: Colors.purple,
      atomicMass: 140.12,
      meltingPoint: 1068,
      boilingPoint: 3716,
      electronegativity: 1.12,
    ),
    PeriodicElement(
      symbol: 'Pr',
      name: 'Praseodymium',
      atomicNumber: 59,
      color: Colors.purple,
      atomicMass: 140.91,
      meltingPoint: 1204,
      boilingPoint: 3793,
      electronegativity: 1.13,
    ),
    PeriodicElement(
      symbol: 'Nd',
      name: 'Neodymium',
      atomicNumber: 60,
      color: Colors.purple,
      atomicMass: 144.24,
      meltingPoint: 1297,
      boilingPoint: 3347,
      electronegativity: 1.14,
    ),
    PeriodicElement(
      symbol: 'Pm',
      name: 'Promethium',
      atomicNumber: 61,
      color: Colors.purple,
      atomicMass: 145,
      meltingPoint: 1315,
      boilingPoint: 3273,
      electronegativity: 1.13,
    ),
    PeriodicElement(
      symbol: 'Sm',
      name: 'Samarium',
      atomicNumber: 62,
      color: Colors.purple,
      atomicMass: 150.36,
      meltingPoint: 1345,
      boilingPoint: 2067,
      electronegativity: 1.17,
    ),
    PeriodicElement(
      symbol: 'Eu',
      name: 'Europium',
      atomicNumber: 63,
      color: Colors.purple,
      atomicMass: 151.96,
      meltingPoint: 1095,
      boilingPoint: 1802,
      electronegativity: 1.20,
    ),
    PeriodicElement(
      symbol: 'Gd',
      name: 'Gadolinium',
      atomicNumber: 64,
      color: Colors.purple,
      atomicMass: 157.25,
      meltingPoint: 1585,
      boilingPoint: 3546,
      electronegativity: 1.20,
    ),
    PeriodicElement(
      symbol: 'Tb',
      name: 'Terbium',
      atomicNumber: 65,
      color: Colors.purple,
      atomicMass: 158.93,
      meltingPoint: 1629,
      boilingPoint: 3503,
      electronegativity: 1.22,
    ),
    PeriodicElement(
      symbol: 'Dy',
      name: 'Dysprosium',
      atomicNumber: 66,
      color: Colors.purple,
      atomicMass: 162.50,
      meltingPoint: 1680,
      boilingPoint: 2840,
      electronegativity: 1.23,
    ),
    PeriodicElement(
      symbol: 'Ho',
      name: 'Holmium',
      atomicNumber: 67,
      color: Colors.purple,
      atomicMass: 164.93,
      meltingPoint: 1734,
      boilingPoint: 2873,
      electronegativity: 1.24,
    ),
    PeriodicElement(
      symbol: 'Er',
      name: 'Erbium',
      atomicNumber: 68,
      color: Colors.purple,
      atomicMass: 167.26,
      meltingPoint: 1802,
      boilingPoint: 3141,
      electronegativity: 1.24,
    ),
    PeriodicElement(
      symbol: 'Tm',
      name: 'Thulium',
      atomicNumber: 69,
      color: Colors.purple,
      atomicMass: 168.93,
      meltingPoint: 1818,
      boilingPoint: 2223,
      electronegativity: 1.25,
    ),
    PeriodicElement(
      symbol: 'Yb',
      name: 'Ytterbium',
      atomicNumber: 70,
      color: Colors.purple,
      atomicMass: 173.05,
      meltingPoint: 1097,
      boilingPoint: 1469,
      electronegativity: 1.10,
    ),
    PeriodicElement(
      symbol: 'Lu',
      name: 'Lutetium',
      atomicNumber: 71,
      color: Colors.purple,
      atomicMass: 174.97,
      meltingPoint: 1925,
      boilingPoint: 3675,
      electronegativity: 1.27,
    ),
    PeriodicElement(
      symbol: 'Hf',
      name: 'Hafnium',
      atomicNumber: 72,
      color: Colors.amber,
      atomicMass: 178.49,
      meltingPoint: 2506,
      boilingPoint: 4876,
      electronegativity: 1.3,
    ),
    PeriodicElement(
      symbol: 'Ta',
      name: 'Tantalum',
      atomicNumber: 73,
      color: Colors.amber,
      atomicMass: 180.95,
      meltingPoint: 3290,
      boilingPoint: 5731,
      electronegativity: 1.5,
    ),
    PeriodicElement(
      symbol: 'W',
      name: 'Tungsten',
      atomicNumber: 74,
      color: Colors.amber,
      atomicMass: 183.84,
      meltingPoint: 3695,
      boilingPoint: 5828,
      electronegativity: 2.36,
    ),
    PeriodicElement(
      symbol: 'Re',
      name: 'Rhenium',
      atomicNumber: 75,
      color: Colors.amber,
      atomicMass: 186.21,
      meltingPoint: 3459,
      boilingPoint: 5869,
      electronegativity: 1.9,
    ),
    PeriodicElement(
      symbol: 'Os',
      name: 'Osmium',
      atomicNumber: 76,
      color: Colors.amber,
      atomicMass: 190.23,
      meltingPoint: 3306,
      boilingPoint: 5285,
      electronegativity: 2.2,
    ),
    PeriodicElement(
      symbol: 'Ir',
      name: 'Iridium',
      atomicNumber: 77,
      color: Colors.amber,
      atomicMass: 192.22,
      meltingPoint: 2719,
      boilingPoint: 4701,
      electronegativity: 2.2,
    ),
    PeriodicElement(
      symbol: 'Pt',
      name: 'Platinum',
      atomicNumber: 78,
      color: Colors.amber,
      atomicMass: 195.08,
      meltingPoint: 2041.4,
      boilingPoint: 4098,
      electronegativity: 2.28,
    ),
    PeriodicElement(
      symbol: 'Au',
      name: 'Gold',
      atomicNumber: 79,
      color: Colors.amber,
      atomicMass: 196.97,
      meltingPoint: 1337.33,
      boilingPoint: 3129,
      electronegativity: 2.54,
    ),
    PeriodicElement(
      symbol: 'Hg',
      name: 'Mercury',
      atomicNumber: 80,
      color: Colors.amber,
      atomicMass: 200.59,
      meltingPoint: 234.32,
      boilingPoint: 629.88,
      electronegativity: 2.00,
    ),
    PeriodicElement(
      symbol: 'Hg',
      name: 'Mercury',
      atomicNumber: 80,
      color: Colors.amber,
      atomicMass: 200.59,
      meltingPoint: 234.32,
      boilingPoint: 629.88,
      electronegativity: 2.00,
    ),
    PeriodicElement(
      symbol: 'Tl',
      name: 'Thallium',
      atomicNumber: 81,
      color: Colors.purple,
      atomicMass: 204.38,
      meltingPoint: 577,
      boilingPoint: 1746,
      electronegativity: 1.62,
    ),
    PeriodicElement(
      symbol: 'Pb',
      name: 'Lead',
      atomicNumber: 82,
      color: Colors.green,
      atomicMass: 207.2,
      meltingPoint: 600.61,
      boilingPoint: 2022,
      electronegativity: 2.33,
    ),
    PeriodicElement(
      symbol: 'Bi',
      name: 'Bismuth',
      atomicNumber: 83,
      color: Colors.green,
      atomicMass: 208.98,
      meltingPoint: 544.7,
      boilingPoint: 1837,
      electronegativity: 2.02,
    ),
    PeriodicElement(
      symbol: 'Po',
      name: 'Polonium',
      atomicNumber: 84,
      color: Colors.green,
      atomicMass: 209,
      meltingPoint: 527,
      boilingPoint: 1235,
      electronegativity: 2.00,
    ),
    PeriodicElement(
      symbol: 'At',
      name: 'Astatine',
      atomicNumber: 85,
      color: Colors.blue,
      atomicMass: 210,
      meltingPoint: 575,
      boilingPoint: 610,
      electronegativity: 2.2,
    ),
    PeriodicElement(
      symbol: 'Rn',
      name: 'Radon',
      atomicNumber: 86,
      color: Colors.cyan,
      atomicMass: 222,
      meltingPoint: 202,
      boilingPoint: 211.3,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Fr',
      name: 'Franclime',
      atomicNumber: 87,
      color: Colors.lime,
      atomicMass: 223,
      meltingPoint: 300,
      boilingPoint: 950,
      electronegativity: 0.7,
    ),
    PeriodicElement(
      symbol: 'Ra',
      name: 'Radium',
      atomicNumber: 88,
      color: Colors.orange,
      atomicMass: 226,
      meltingPoint: 973,
      boilingPoint: 2010,
      electronegativity: 0.9,
    ),
    PeriodicElement(
      symbol: 'Ac',
      name: 'Actinium',
      atomicNumber: 89,
      color: Colors.purple,
      atomicMass: 227,
      meltingPoint: 1323,
      boilingPoint: 3471,
      electronegativity: 1.1,
    ),
    PeriodicElement(
      symbol: 'Th',
      name: 'Thorium',
      atomicNumber: 90,
      color: Colors.red,
      atomicMass: 232.04,
      meltingPoint: 2023,
      boilingPoint: 5061,
      electronegativity: 1.3,
    ),
    PeriodicElement(
      symbol: 'Pa',
      name: 'Protactinium',
      atomicNumber: 91,
      color: Colors.red,
      atomicMass: 231.04,
      meltingPoint: 1841,
      boilingPoint: 4300,
      electronegativity: 1.5,
    ),
    PeriodicElement(
      symbol: 'U',
      name: 'Uranium',
      atomicNumber: 92,
      color: Colors.red,
      atomicMass: 238.03,
      meltingPoint: 1405.3,
      boilingPoint: 4200,
      electronegativity: 1.38,
    ),
    PeriodicElement(
      symbol: 'Np',
      name: 'Neptunium',
      atomicNumber: 93,
      color: Colors.red,
      atomicMass: 237,
      meltingPoint: 917,
      boilingPoint: 4273,
      electronegativity: 1.36,
    ),
    PeriodicElement(
      symbol: 'Pu',
      name: 'Plutonium',
      atomicNumber: 94,
      color: Colors.red,
      atomicMass: 244,
      meltingPoint: 913,
      boilingPoint: 3505,
      electronegativity: 1.28,
    ),
    PeriodicElement(
      symbol: 'Am',
      name: 'Americium',
      atomicNumber: 95,
      color: Colors.red,
      atomicMass: 243,
      meltingPoint: 1449,
      boilingPoint: 2880,
      electronegativity: 1.3,
    ),
    PeriodicElement(
      symbol: 'Cm',
      name: 'Curium',
      atomicNumber: 96,
      color: Colors.red,
      atomicMass: 247,
      meltingPoint: 1613,
      boilingPoint: 3383,
      electronegativity: 1.3,
    ),
    PeriodicElement(
      symbol: 'Bk',
      name: 'Berkelium',
      atomicNumber: 97,
      color: Colors.red,
      atomicMass: 247,
      meltingPoint: 1323,
      boilingPoint: 2900,
      electronegativity: 1.3,
    ),
    PeriodicElement(
      symbol: 'Cf',
      name: 'Californium',
      atomicNumber: 98,
      color: Colors.red,
      atomicMass: 251,
      meltingPoint: 1173,
      boilingPoint: 1743,
      electronegativity: 1.3,
    ),
    PeriodicElement(
      symbol: 'Es',
      name: 'Einsteinium',
      atomicNumber: 99,
      color: Colors.red,
      atomicMass: 252,
      meltingPoint: 1133,
      boilingPoint: 1269,
      electronegativity: 1.3,
    ),
    PeriodicElement(
      symbol: 'Fm',
      name: 'Fermium',
      atomicNumber: 100,
      color: Colors.red,
      atomicMass: 257,
      meltingPoint: 1800,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Md',
      name: 'Mendelevium',
      atomicNumber: 101,
      color: Colors.red,
      atomicMass: 258,
      meltingPoint: 1100,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'No',
      name: 'Nobelium',
      atomicNumber: 102,
      color: Colors.red,
      atomicMass: 259,
      meltingPoint: 1100,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Lr',
      name: 'Lawrencium',
      atomicNumber: 103,
      color: Colors.red,
      atomicMass: 262,
      meltingPoint: 1900,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Rf',
      name: 'Rutherfordium',
      atomicNumber: 104,
      color: Colors.amber,
      atomicMass: 267,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Db',
      name: 'Dubnium',
      atomicNumber: 105,
      color: Colors.amber,
      atomicMass: 270,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Sg',
      name: 'Seaborgium',
      atomicNumber: 106,
      color: Colors.amber,
      atomicMass: 271,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Bh',
      name: 'Bohrium',
      atomicNumber: 107,
      color: Colors.amber,
      atomicMass: 274,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Hs',
      name: 'Hassium',
      atomicNumber: 108,
      color: Colors.amber,
      atomicMass: 277,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Mt',
      name: 'Meitnerium',
      atomicNumber: 109,
      color: Colors.amber,
      atomicMass: 278,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Ds',
      name: 'Darmstadtium',
      atomicNumber: 110,
      color: Colors.amber,
      atomicMass: 281,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Rg',
      name: 'Roentgenium',
      atomicNumber: 111,
      color: Colors.amber,
      atomicMass: 282,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Cn',
      name: 'Copernicium',
      atomicNumber: 112,
      color: Colors.amber,
      atomicMass: 285,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Nh',
      name: 'Nihonium',
      atomicNumber: 113,
      color: Colors.purple,
      atomicMass: 286,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Fl',
      name: 'Flerovium',
      atomicNumber: 114,
      color: Colors.green,
      atomicMass: 289,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Mc',
      name: 'Moscovium',
      atomicNumber: 115,
      color: Colors.green,
      atomicMass: 290,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Lv',
      name: 'Livermorium',
      atomicNumber: 116,
      color: Colors.green,
      atomicMass: 293,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Ts',
      name: 'Tennessine',
      atomicNumber: 117,
      color: Colors.blue,
      atomicMass: 294,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
    PeriodicElement(
      symbol: 'Og',
      name: 'Oganesson',
      atomicNumber: 118,
      color: Colors.cyan,
      atomicMass: 294,
      meltingPoint: null,
      boilingPoint: null,
      electronegativity: null,
    ),
  ]
];
